apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups:
    - 4000
  containers:
  - image: busybox
    name: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: nfs-vol
      mountPath: /var/nfs # The mountpoint inside the container
    securityContext:
      capabilities:
        drop:
          - ALL
      allowPrivilegeEscalation: false
    resources:
      limits:
        cpu: 1
        memory: 100Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: nfs-vol 
    nfs:
      server: 10.96.253.91 # IP to our NFS server
      path: /export # The exported directory
